<?php $_menu = $this->getHtml('level-top');?>
<div class="mobMenu span12">
<h1>
<a href="javascript:void(0);" class="menuBox highlight">
	<span class="sp1"></span>
	<span class="sp2"></span>
	<span class="sp3"></span>
</a>
<span class="clearfix"></span>
</h1>
<div id="menuInnner">
<?php if ($_menu): ?>
		<ul class="accordion">
			<?php echo $_menu; ?>
		</ul>
<?php endif ?>
      
</div>      
</div>