<?php $config = Mage::getStoreConfig('mdlpump/homeproducts');?>
<?php $config2 = Mage::getStoreConfig('mdloption/genral_theme_setting'); ?>

<?php 
    $categoryId = $config['category_id'];
	$cObj = Mage::getModel('catalog/category')->load($categoryId);
	$visibility = array(
            Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
            Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
    );
	$productObj = $cObj->getProductCollection()->addAttributeToFilter('visibility', $visibility)->setPageSize($config['total_pro']);
    $_helper = $this->helper('catalog/output');
?>

			<?php if($config['row_pro']=='1'):?>
				<?php $imgSize = '800'?>
			<?php elseif ($config['row_pro']=='2'):?>
				<?php $imgSize = '600'?>
			<?php elseif ($config['row_pro']=='3'):?>
				<?php $imgSize = '400'?>
			<?php elseif ($config['row_pro']=='4'):?>
				<?php $imgSize = '300'?>
			<?php elseif ($config['row_pro']=='5'):?>	
				<?php $imgSize = '300'?>
			<?php else:?>
				<?php $imgSize = '200'?>
			<?php endif; ?>
			
			
  <div class="jcarousel">
    <div class="products-grid scrollerRfy">

      <?php $i=1; foreach($productObj as $_productData): ?>
      <?php $_product = Mage::getModel('catalog/product')->load($_productData['entity_id']); ?>
      
		 
		<?php if($config['flip_view']==1 && $config['flip_view_style']==2):?>
			<?php $flipviewStyleL='fadeView'; ?>
		<?php endif; ?>
	<div data-galcounter="<?php echo $i;?>" class="item galView fifthView  galboxntp<?php echo $i;?>">
		<div class="itemInner areaBox">
					
                <!--Images and price container-->
                    <div class="proImage <?php echo $flipviewStyleL; ?> flipView">
						<!--Badge view-->
							<div class="badgeBox">
									<!--New badge-->
									<?php if($_product->getData('mdl_new')):?>
										<span class="new">
											<strong><?php echo $this->__('new')?></strong>
										</span>
									<?php endif;?>
									<!--End new badge-->
							</div>	
						<!--end badge view-->
						
						
						<!--Sale badge view-->
							<?php if($_product->getSpecialPrice()): ?>
                                <?php echo Mage::helper("myfunction")->specialPriceDiscount($_product); ?>
                            <?php endif; ?>
                        <!--End sale badge view-->
						                        
						
                   		    <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
                            </a>
						
                         
						
						
					
                          <!--Quick links-->
                           <div class="lowPanel">
                           		<div class="lowPanelin">
                           		 <?php if($config['itemviewbox_quick_view']==1):?>
									  <?php if($_product->isSaleable()): ?>
										  <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
										  <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i> <?php echo $this->__('Add to cart') ?></span></span></button>
										  <?php else: ?>
										  <a title="<?php echo $this->__('Add to Cart') ?>"  href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox add-cart' id='fancybox<?php echo $_product->getId();?>'><span><span><?php echo $this->__('Add to cart') ?></span></span></a>
										  <?php endif; ?>
									  <?php else: ?>
										   <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									  <?php endif;?>
								<?php else: ?>
									  <?php if($_product->isSaleable()): ?>
									  <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i> <?php echo $this->__('Add to Cart') ?></span></span></button>
									  <?php else: ?>
									  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									  <?php endif; ?>
								<?php endif; ?>
                                
                                <!--Gallery View Button-->    
                                <?php if(($config['gallery_view']==1)):?> 	
                                	<a href="javascript:void(0);" class="galleryBtn"><?php echo $this->__('View Gallery');?></a>
                                <?php endif; ?>
                                <!--End Gallery View Button-->    
								</div>
						  </div> 
                          <!--End Quick links-->
						  
					
                    </div>
				<!--End images and price container--> 
                
                
                 
                
                
				<!--Product detail container-->  
				<div class="bottomProDetail">
					<h2 class="product-name"> 
                    	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"> 
                        	<?php if($config['name_character']!=''):?>
                            	<?php echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'),0, $config['name_character'])?>
                            <?php else:?>
                            	<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> 
                            <?php endif;?>        
                        </a> 
                    </h2>
					
					
                    <!--Price-->  
                        <?php echo $this->getPriceHtml($_product, true, '-right') ?>
					<!--End price--> 
                    
                    
                    <div class="lpBottom">
                    	<!--Quick view icon-->
								  <?php if($config['itemviewbox_quick_view']==1):?>
                                  <a  title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox qv-btn w-btn' id='fpfancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i></a>
                                  <?php endif; ?>
                         <!--End quick view icon-->
                        
                        <!--Comapare-->
                        <?php if ($config2['compare_box']) :?>
                             <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                  <a href="javascript:void(0);" class="w-btn" onclick="setLocation('<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" > 
                                        <i class="fa fa-clone"></i> 
                                  </a>
                             <?php endif; ?>
                        <?php endif; ?>	 
                        <!--End comapare-->
                          
                        <!--wishlist-->
                              <?php if ($this->helper('wishlist')->isAllow()) : ?>
                              <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>"  class="w-btn">
                                 <i class="fa fa-heart"></i>
                              </a>
                              <?php endif; ?>
                        <!--End wishlist-->
                        
                        <!-- Rating -->
                            <?php echo $this->getReviewsSummaryHtml($_product, "short", true)?>
                        <!-- End rating -->
                        
                        <!-- Color swatch -->
						<?php if ($this->getChild('name.after')):?>
                            <?php $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();?>
                            <?php foreach ($_nameAfterChildren as $_nameAfterChildName):?>
                                <?php $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);?>
                                <?php $_nameAfterChild->setProduct($_product);?>
								<?php if(($_nameAfterChild->toHtml())!=''):?>
									<div class="listColorSwatch">
										<h3><?php echo $this->__('Color');?></h3>
										<?php echo $_nameAfterChild->toHtml();?>
									</div>
								<?php endif;?>	
                            <?php endforeach ?>
                        <?php endif;?>
                        <!--End Color swatch --> 
                         
                    </div>
                    
					
                </div>
                <!--End product detail container-->     
        </div>
        	
            <!--Gallery View Container-->    
              <?php if(($config['gallery_view']==1)):?> 
            <div class="galleryBox">
            	<a class="closeGallery" href="javascript:void(0);"></a>
                <div class="listGallery">
                    <?php $media_gallery = $_product->getMediaGallery(); ?>
                            <?php foreach ($media_gallery['images'] as $_image):?>
                            <div class="list">
								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image', $_image['file'])->resize(300); ?>" alt="<?php echo $this->escapeHtml($_image['label']) ?>" />
                            </div>
                            <?php endforeach; ?>
                            </div>
                </div>
                <?php endif;?>  
             <!--End Gallery View Container-->   
	</div>		
		

        
      <?php $i++; endforeach;?>
    </div>
  </div>

<script type="text/javascript">
(function($){
    $(function() {

		$('.scrollerRfy').owlCarousel({
					loop:true,
					smartSpeed: 500,
					dots: false,
					margin:10,
					navText: ["<i class='fa fa-angle-left'></i>", "<i class='fa fa-angle-right'></i>" ],
					responsiveClass:true,
					responsive:{
						0:{
							items:1,
							nav: true
						},
						600:{
							items:3,
							nav: true
						},
						1000:{
							items:<?php echo $config['row_pro'];?>,
							nav: true,
							loop:true
						}
					}
				})
	
	
    });
	
})(jQuery);			
</script>

 <script type="text/javascript">
		(function($){
			$(function(){
					$('.scrollerRfy .listGallery').owlCarousel({
					loop:false,
					smartSpeed: 500,
					margin:10,
					dots: false,
					nav: true,
					navText: ["<i class='fa fa-angle-left'></i>", "<i class='fa fa-angle-right'></i>" ],
					responsiveClass:true,
					items:1
				})
				;
					
			});
			
			$('div.item').each(function(index,v){
				var i = $(v).data('galcounter');
				$(document).on('click','div.galboxntp'+i+' a.galleryBtn',function(){
					$('div.item').addClass('galView');
					$('div.galboxntp'+i).removeClass('galView');
					return false;
				});
				$(document).on('click','div.galboxntp'+i+' a.closeGallery',function(){
					$('div.galboxntp'+i).addClass('galView');
					return false;
				});
			});
			
		})(jQuery);			
		</script>