<?php $posts = $this->getPosts(); ?>
<?php if (count($posts)): ?>
 <?php echo $this->getChildHtml('magic_mdlblog_comments_toolbar'); ?>
<div class="f-block blog-wrapper">
	<div class="row">
    <?php foreach ($posts as $post): ?>
        <div class="col-sm-4">
            <div class="blogItem">
				<div class="date-block"><?php echo $post->getCreatedTime(); ?></div>
				<h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
				<div class="img-block">
				<a href="<?php echo $post->getAddress(); ?>" >
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $post->getBlogthumb(); ?>" alt=""/>
				</a>
				</div>
				<div class="blog-short-dec">
					<?php 
					   $desc = $post->getPostContent();
					   $text = substr(strip_tags($desc),0,100);
					   echo $text; 
					?>
					
					
				</div>
				<ul class="f-block bList">
					<li>
					<?php if ($this->getCommentsEnabled()): ?>
						<span class="read-more">
							<a href="<?php echo $post->getAddress(); ?>#commentBox" ><?php if($post->getCommentCount()) { ?> <?php echo $post->getCommentCount(); ?> <?php } else { echo '0 '; } ?> Comments</a>
							</span><strong>|</strong>
						<?php endif; ?>
					</li>
					<li>
						<span class="read-more">
					<?php $postCats = $post->getCats(); ?>
                        <?php if (!empty($postCats)): ?>
                            <?php foreach ($postCats as $data): ?>
                                    <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <?php echo Mage::helper('mdlblog')->__('Posted'); ?>
                        <?php endif; ?>
						</span>
						<strong>|</strong>
					</li>
					<li>
						<span class="read-more"><?php echo $post->getUser(); ?></span>
					</li>
				</ul>
						
				<div class="blogInner">
					<?php echo $this->getBookmarkHtml($post) ?>
                    <div class="tags"><?php echo Mage::getBlockSingleton('mdlblog/mdlblog')->getTagsHtml($post) ?></div>
                    
					<div class="postDetails">
                        
                        
                        
							
						</div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
</div>
 <?php echo $this->getChildHtml('magic_mdlblog_comments_toolbar'); ?>
<?php else: ?>
    <?php echo Mage::helper('mdlblog')->__('No Posts in this Category.'); ?>
<?php endif; ?>
