<?php $posts = $this->getPosts(); ?>

<div id="messages_product_view">
  <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
  <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?> </div>
<div class="page-title">
  <h1>Blog</h1>
</div>
<?php echo $this->getChildHtml('magic_mdlblog_comments_toolbar'); ?>
<?php
//print_r(get_obj_vars($posts));die;
$post_array = array();
foreach($posts as $post){
	$post_array[] = $post;
}

$post_count = Mage::getStoreConfig('mdlblog/bloglist/bloglistoption'); ;
$post_chunk = array_chunk($post_array, $post_count);
foreach($post_chunk as $posts):
?>
<div class="f-block blog-wrapper">
<ul class="blogListStyle<?php echo $post_count?> bloglistveiw row">
  <?php
 foreach ($posts as $post): ?>
  <li class="col-xs-12 blog-list <?php if($post_count =='2'):?>col-sm-6<?php endif;?> <?php if($post_count =='3'):?>col-md-4<?php endif;?>">
  	<div class="blogItem">
		<div class="date-block"><?php echo date('M', strtotime($post->getCreatedTime())); ?> <?php echo date('d', strtotime($post->getCreatedTime())); ?></div>
	    <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
    <div class="postContent f-fix">
      <div class="f-block"> 
      	<a href="<?php echo $post->getAddress(); ?>" > 
        	<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $post->getBlogimage(); ?>" alt="" width="100%"/>
        </a>
      </div>
	  
	  <ul class="f-block bList">
		  	<li><span class="author"><?php echo $post->getUser(); ?></span><strong>|</strong></li>
            <li>
				<span class="read-more">
				<a href="<?php echo $post->getAddress(); ?>#commentBox" >
				<?php if ($this->getCommentsEnabled()): ?>
              <?php if($post->getCommentCount()) { ?>
              <?php echo $post->getCommentCount(); ?>
              <?php } else { echo '0 '; } ?>
               Comments</a>
              <?php endif; ?>
			  </span>
			  <strong>|</strong>
            </li>
            <li>
              <?php $postCats = $post->getCats(); ?>
              <?php if (!empty($postCats)): ?>
              <?php foreach ($postCats as $data): ?>
              		<a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
              <?php endforeach; ?>
           
            <?php else: ?>
            	<?php echo Mage::helper('mdlblog')->__('Posted'); ?>
            <?php endif; ?>
             </li>
             
            		
          </ul>
	  
	  
	  <div class="blog-short-dec">
	   		<?php if((Mage::getStoreConfig('mdlblog/bloglist/useshortcontent')==1)):?>
				<?php 
                   $desc = $post->getPostContent();
                   $text = substr(strip_tags($desc),0,250);
                   echo $text; 
                ?>
        	 <?php endif?>
	  </div>
      
      </div>
    </div>
  </li>
  <?php endforeach; ?>
</ul>
</div>
<?php endforeach; ?>
<?php echo $this->getChildHtml('magic_mdlblog_comments_toolbar'); ?> 