<?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="postWrapper f-block">
    <div class="block-title">
    	    <h2><?php echo $post->getTitle(); ?></h2>
    </div>
    
    <div class="postContent blog-wrapper">
		<div class="blogItem">
			<img class="mainpost" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $post->getBlogimage(); ?>" alt="" />
			<ul class="f-block bList">
					<li><?php echo date('M d, Y', strtotime($post->getCreatedTime())); ?><strong>|</strong></li>
					<li>
						<span class="read-more">
						<?php $postCats = $post->getCats(); ?>
						<?php if (!empty($postCats)): ?>
						<?php foreach ($postCats as $title => $url): ?>
						<a href="<?php echo $url; ?>"><?php echo $title; ?></a>
						<?php endforeach; ?>
						</span>
						<strong>|</strong>
					</li>
					<li><span class="author">
					<?php else: ?>
					<?php //echo Mage::helper('mdlblog')->__('Posted'); ?>
					<?php endif; ?><?php echo $post->getUser(); ?></span>
					</li>
				</ul>
			<div class="blog-short-dec"><?php echo $post->getPostContent(); ?></div>
		</div>
    </div>
</div>

<!-- Comment Section -->
<div class="f-block blog-post-wrapper">
<?php if ($this->getCommentsEnabled()): ?>
    <?php $comments = $this->getComment(); ?>
    <div class="block-title">
	        <h2><?php echo $this->__('Post Comments') ?></h2>
    </div>
    <?php echo $this->getChildHtml('magic_mdlblog_comments_toolbar'); ?>
        <?php foreach ($comments as $comment) : ?>
    	<ul class="blog-comments">
            <li class="commentWrapper">
            	<h4><a href="#" title=""><?php echo $comment->getUser(); ?></a></h4>
				<div class="date-block"><?php echo date('M d, Y', strtotime($post->getCreatedTime())); ?></div>
                <div class="blog-short-dec"><p><?php echo nl2br($comment->getComment()); ?></p></div>
            </li>
        </ul>
        <?php endforeach; ?>
     <?php echo $this->getChildHtml('magic_mdlblog_comments_toolbar'); ?>
<div class="f-block blog-form">

    <?php if ($post->getComments()): ?>
        <div class="postError"><?php echo Mage::helper('mdlblog')->__('Comments are Closed for this post') ?></div>
    <?php else: ?>
        <?php if ($this->getLoginRequired()): ?>
            <?php if ($this->helper('customer')->isLoggedIn()): ?>
                <form action="" id="postComment" method="post">
                    <fieldset class="group-select">
                        <h4 class="legend"><?php echo Mage::helper('mdlblog')->__('Submit Comment') ?></h4>
                        <ul class="form-list">
                            <li class="fields">
                                <div class="input-box magic-mdlblog-comment-area">
                                    <label for="comment" class="required"><?php echo Mage::helper('mdlblog')->__('Comment') ?><em>*</em></label><br />
                                    <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                    <div class="button-set" style="width:96%">
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('mdlblog')->getUserEmail()) ?>"/>
                        <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('mdlblog')->getUserName()) ?>"/>
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <button class="form-button button" type="submit"><span><span><?php echo Mage::helper('mdlblog')->__('Submit Comment') ?></span></span></button>
                    </div>
                </form>

                <script type="text/javascript">
                    var contactForm = new VarienForm('postComment', false);
                </script>

            <?php else: ?>
                <p><?php echo Mage::helper('mdlblog')->__('You must be logged in to post a comment.'); ?></p>
                <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('mdlblog')->__('click here'); ?></a> <?php echo Mage::helper('mdlblog')->__('to log in'); ?></p>
            <?php endif ?>

        <?php else: ?>

            <form action="" id="postComment" method="post">
                <fieldset class="group-select">
                    <h4 class="legend"><?php echo Mage::helper('mdlblog')->__('Submit Comment') ?></h4>
                    <ul class="form-list">
                        <li class="fields">
                            <div class="field">
                                <label for="name" class="required"><?php echo Mage::helper('mdlblog')->__('Name') ?><em>*</em></label><br />
                                <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
                            </div>
                            <div class="field">
                                <label for="email" class="required"><?php echo Mage::helper('mdlblog')->__('Email') ?><em>*</em></label><br />
                                <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" />
                            </div>
						</li>
                        <li class="wide">

                                <label for="comment" class="required"><?php echo Mage::helper('mdlblog')->__('Comment') ?><em>*</em></label><br />
                                <textarea name="comment" id="comment" title="<?php echo Mage::helper('mdlblog')->__('Comment') ?>" class="required-entry input-text" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                        </li>

                        <?php
                        if (Mage::getStoreConfig('mdlblog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
                            ?><li><?php
                require_once 'recaptcha/recaptchalib-magic.php';

                // Get a key from http://recaptcha.net/api/getkey
                $publickey = Mage::getStoreConfig('mdlblog/recaptcha/publickey');
                $privatekey = Mage::getStoreConfig('mdlblog/recaptcha/privatekey');
                $error = null;

                echo recaptcha_get_html($publickey, $error);
                            ?></li><?php
            }
                        ?>
                    </ul>
                </fieldset>
                <div class="buttons-set">
                    <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <button class="button form-button" type="submit"><span><span><?php echo Mage::helper('mdlblog')->__('Submit Comment') ?></span></span></button>
                </div>
            </form>

            <script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>
        <?php endif; ?>
    </div>
    <?php endif; ?>
<?php endif; ?>
</div>