<?php 
$config = Mage::getStoreConfig('mdloption/homeproducts');
$config2 = Mage::getStoreConfig('bestsellingproduct/jqueryfile');
$config3 = Mage::getStoreConfig('mdloption/genral_theme_setting');
$config4 = Mage::getStoreConfig('bestsellingproduct/mostviewed');

$id = $this->getRequest()->getParam('tabid');

// Check if clicked tab is bestseller
if($id=='tab-bestseller')
{
	$_product_new = $this->getLayout()->getBlockSingleton('Mdl_Bestseller_Block_Bestsellingproduct');
			$new_product=$_product_new->getProductCollection();
			$count_product = count($new_product);
			$jcarousel_status = Mage::helper('bestsellingproduct')->getBestsellingJcarousel();
}
// Check if clicked tab is new product
else if($id=='tab-newproduct')
{
	$_product_new = $this->getLayout()->getBlockSingleton('Mdl_Bestseller_Block_Newproduct');
			$new_product=$_product_new->getProductCollection();
			$count_product = count($new_product);
			$jcarousel_status = Mage::helper('bestsellingproduct')->getNewproductJcarousel();
}
// Check if clicked tab is featured
else if($id=='tab-featured')
{
	$new_product = Mage::getModel('catalog/product')->getCollection();
		   $attributes = Mage::getSingleton('catalog/config')
			->getProductAttributes();
		   $new_product->addAttributeToSelect($attributes)
			->addMinimalPrice()
			->addFinalPrice()
			->addTaxPercents()
						->addAttributeToFilter(array(array( // Flat Catalog Product workaround
							'attribute' => 'mdl_featured',
							'eq' => 1,
						)), null, 'left')
			->addStoreFilter()->setPageSize($config4['total_pro']);
		   Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($new_product);
		   Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($new_product);
		   Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($new_product);
		  $_helper = $this->helper('catalog/output');	
		  $count_product = count($new_product);
		  $jcarousel_status = Mage::helper('bestsellingproduct')->getFeaturedJcarousel();
}
else
{
	$_product_new = $this->getLayout()->getBlockSingleton('Mdl_Bestseller_Block_Bestsellingproduct');
			$new_product=$_product_new->getProductCollection();
			$count_product = count($new_product);
			$jcarousel_status = Mage::helper('bestsellingproduct')->getBestsellingJcarousel();
}

			 ?>
			 
			  <?php if($config2['rowPro']=='1'):?>
				<?php $itemwidth = 'col-xs-6 col-sm-6'; $proCount = '2';?>
				<?php $imgSize = '600'?>
			  <?php elseif ($config2['rowPro']=='2'):?>
				<?php $itemwidth = 'col-sm-4';  $proCount = '3'; ?>
				<?php $imgSize = '400'?>
			  <?php elseif ($config2['rowPro']=='3'):?>
				<?php $itemwidth = 'col-xs-6 col-sm-3 col-md-3';  $proCount = '4'; ?>
				<?php $imgSize = '300'?>
			  <?php elseif ($config2['rowPro']=='4'):?>
				<?php $itemwidth = 'col-xs-6 col-sm-4 col-md-2' ;  $proCount = '6'; ?>
				<?php $imgSize = '200'?>
			  <?php endif; ?>
             
            <?php if($config2['flip_view']==1 && $config2['flip_view_style']==2):?>
				<?php $flipviewStylef='fadeView'; ?>
              <?php endif; ?> 
            

				<?php
				$new_product1 = array();
			    foreach ($new_product  as  $key=>$new)
				{
					$new_product1[] = $new;
				}
				$config['rowPro']==$proCount;
				$new_product2 = array_chunk($new_product1,$proCount);
				foreach($new_product2 as $new_product){ ?>
				<ul class="newProducts itemPro products-grid">
				

				
				<?php foreach ($new_product  as  $key=>$new) {?>
	<li class="item fourthView <?php echo $itemwidth ?>">
			<div class="itemInner areaBox">
					
                <!--Images and price container-->
                    <div class="proImage <?php echo $flipviewStyleL; ?> flipView">
						<!--Badge view-->
							<div class="badgeBox">
									<!--New badge-->
									<?php if($new->getData('mdl_new')):?>
										<span class="new">
											<strong><?php echo $this->__('new')?></strong>
										</span>
									<?php endif;?>
									<!--End new badge-->
							</div>	
						<!--end badge view-->
						
						
						<!--Sale badge view-->
							<?php if($new->getSpecialPrice()): ?>
                                <?php echo Mage::helper("myfunction")->specialPriceDiscount($new); ?>
                            <?php endif; ?>
                        <!--End sale badge view-->
						
						
                   		<?php if($config['flip_view']==1):?>
							<a href="<?php echo $new->getProductUrl() ?>" class="product-image"> 
							<img class="spacer-img" src="<?php echo $this->getSkinUrl('images/spacer.png');?>" title="" alt="" />
							<span class="face">
							<img id="product-collection-image-<?php echo $new->getId(); ?>" class="front-img" src="<?php echo $this->helper('catalog/image')->init($new, 'small_image')->resize($imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($new, 'small_image'), null, true) ?>"  />
							</span>
							<span class="back-img back face">
								<img class="hoverImg" src="<?php echo Mage::helper('catalog/image')->init($new, 'thumbnail')->resize($imgSize); ?>" 
								alt="<?php echo $this->htmlEscape($new['name']); ?>"  />
							</span> 
							</a>
                        <?php else: ?>
                            <a href="<?php echo $new->getProductUrl() ?>" class="product-image"> 
                                <img id="product-collection-image-<?php echo $new->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($new, 'small_image')->resize($imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($new, 'small_image'), null, true) ?>" /> 
                            </a>
						<?php endif; ?>
                        
                          <!--Quick view icon-->
								  <?php if($config2['itemviewbox_quick_view']==1):?>
								  <a  title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$new->getId()));?>' class='fancybox qv-btn' id='fpfancybox<?php echo $new->getId();?>'><i class="fa fa-search"></i></a>
								  <?php endif; ?>
						 <!--End quick view icon-->
						
						
					
                          <!--Quick links-->
                           <div class="actionBox">
                           		 <?php if($config['itemviewbox_quick_view']==1):?>
									  <?php if($new->isSaleable()): ?>
										  <?php if ( !($new->getTypeInstance(true)->hasRequiredOptions($new) || $new->isGrouped()) ): ?>
										  <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($new) ?>')"><span><span><i class="fa fa-shopping-cart"></i> <?php echo $this->__('Add to cart') ?></span></span></button>
										  <?php else: ?>
										  <a title="<?php echo $this->__('Add to Cart') ?>"  href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$new->getId()));?>' class='fancybox add-cart' id='fancybox<?php echo $new->getId();?>'><span><span><i class="fa fa-shopping-cart"></i> <?php echo $this->__('Add to cart') ?></span></span></a>
										  <?php endif; ?>
									  <?php else: ?>
										   <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									  <?php endif;?>
								<?php else: ?>
									  <?php if($new->isSaleable()): ?>
									  <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($new) ?>')"><span><span><i class="fa fa-shopping-cart"></i> <?php echo $this->__('Add to Cart') ?></span></span></button>
									  <?php else: ?>
									  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									  <?php endif; ?>
								<?php endif; ?>
                                 	
                                
								 <!--Comapare-->
								<?php if ($config3['compare_box']) :?>
									 <?php if($_compareUrl=$this->getAddToCompareUrl($new)): ?>
										  <a href="javascript:void(0);" class="w-btn" onclick="setLocation('<?php echo $_compareUrl?>','<?php echo $new->getId()?>'); return false;" > 
												<i class="fa fa-clone"></i> 
										  </a>
									 <?php endif; ?>
								<?php endif; ?>	 
								<!--End comapare-->
								  
								<!--wishlist-->
									  <?php if ($this->helper('wishlist')->isAllow()) : ?>
									  <a href="<?php echo $this->helper('wishlist')->getAddUrl($new) ?>" title="<?php echo $this->__('Add to Wishlist') ?>"  class="w-btn">
										 <i class="fa fa-heart"></i>
									  </a>
									  <?php endif; ?>
								 <!--End wishlist-->
								
								</div> 
                          <!--End Quick links-->
						  
					
                    </div>
				<!--End images and price container--> 
                
				<!--Product detail container-->  
				
				
                <div class="bottomProDetail">
					
					<h2 class="product-name"> 
                    	<a href="<?php echo $new->getProductUrl() ?>" title="<?php echo $this->stripTags($new->getName(), null, true) ?>"> 
                        	<?php if($config2['name_character']!=''):?>
                            	<?php echo substr($new->getName(),0, $config2['name_character']);?>
                            <?php else:?>
                            	<?php echo $new->getName();?>
                            <?php endif;?>        
                        </a> 
                    </h2>
					
					<!-- Rating -->
                        <?php echo $this->getReviewsSummaryHtml($new, "short", true)?>
                    <!-- End rating -->
					
                    <!--Price-->  
                        <?php echo $this->getPriceHtml($new, true, '-right') ?>
					<!--End price--> 
					
                </div>
                <!--End product detail container-->     
        </div>
	</li>	
				
			  
				<?php }?>
				</ul>
			<?php } ?>
			
			<?php //} ?>	
