<?php $config = Mage::getStoreConfig('mdlpump/featuredpro');?>
<?php $config2 = Mage::getStoreConfig('mdloption/genral_theme_setting'); ?>
<?php 
         $collection = Mage::getModel('catalog/product')->getCollection();
		   $attributes = Mage::getSingleton('catalog/config')
			->getProductAttributes();
		   $collection->addAttributeToSelect($attributes)
			->addMinimalPrice()
			->addFinalPrice()
			->addTaxPercents()
						->addAttributeToFilter(array(array( // Flat Catalog Product workaround
							'attribute' => 'mdl_featured',
							'eq' => 1,
						)), null, 'left')
			->addStoreFilter()->setPageSize($config['total_pro']);
		   Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($collection);
		   Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($collection);
		   Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($collection);
		  $_helper = $this->helper('catalog/output');	
		 
		
 ?>
 
<div class="blocks featured-left">
  <div class="block-title">
	  <h2><span><?php echo $config['heading']?></span></h2>
  </div>
<div class="jcarousel-wrapper">  
  <div class="jcarousel">
    <div class="scrollerfpl">
	<?php
	$cc = 4;
	$items = $collection->getData();
	$_itemCounts = count($items);
	$items = array_chunk($items, $cc);
	$divider = $_itemCounts < $cc ? $_itemCounts : $cc;
	$rep = ceil($_itemCounts/$divider);
	for($_j=0;$_j<$rep;$_j++):
	?>
		<div class="item">
			<?php for($_k=0;$_k<$divider;$_k++):?>
			<?php if(isset($items[$_j][$_k]['entity_id'])): ?>
			<?php $_product = Mage::getModel('catalog/product')->load($items[$_j][$_k]['entity_id']); ?>
			
				<div class="featuredLeft">
					 <div class="proImage">
						 <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
                         </a>
					  </div>
					 <div class="bottomProDetail">
						<h2 class="product-name">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"> 
                            	<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> 
                         </a> 
						</h2>
						<!-- Rating -->
							<?php echo $this->getReviewsSummaryHtml($_product, "short", true)?>
						<!-- End rating -->
						
						<!--Price-->  
							<?php echo $this->getPriceHtml($_product, true, '-right') ?>
						<!--End price--> 
					 </div>
				</div>
			<?php endif; ?>
			
			<?php endfor; ?>
		</div>
	<?php
	endfor;
	?>
    </div>
  </div>
	</div>  
</div>  

<script type="text/javascript">
(function($){
    $(function() {

		$('.scrollerfpl').owlCarousel({
					loop:true,
					smartSpeed: 500,
					dots: false,
					margin:0,
					navText: ["<i class='fa fa-angle-left'></i>", "<i class='fa fa-angle-right'></i>" ],
					responsiveClass:true,
					items:1,
					autoHeight: true,
					nav: true,
					autoplay:true,
					autoplayTimeout:5000,
					autoplayHoverPause:true
				})
	
	
    });
	
})(jQuery);			
</script>