<?php $config = Mage::getStoreConfig('mdlpump/qnew');?>
<?php if($config['quick_new_settings']):?>
<?php 
  $visibility = array(
	  Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
	  Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
  ); 
  $todayDate  = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
  $_productCollection = Mage::getResourceModel('catalog/product_collection')
  ->addAttributeToSelect('*')
  ->addAttributeToFilter('visibility', $visibility)
  ->addAttributeToFilter('status', 1)
  ->addAttributeToFilter('news_from_date', array('date' => true, 'to' => $todayDate))
  ->addAttributeToFilter('news_to_date', array('or'=> array(
  0 => array('date' => true, 'from' => $todayDate),
  1 => array('is' => new Zend_Db_Expr('null')))
  ), 'left');
  $_productCollection->setOrder('entity_id', 'desc');
  $_productCollection->setPageSize($config['quick_new_column']); 
  Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($_productCollection);
  $_helper = $this->helper('catalog/output');
        //echo 'coun='.count($_productCollection);
 ?>
 
<div class="col-md-3 col-sm-6">
	<div class="block-title">
	  <h2><span><?php echo $config['quick_new_heading']?></span></h2>
	</div>
	<?php if(count($_productCollection)==0):?>	
		<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
	<?php else:?>
	
	<ul class="quick_products">
	  <?php $i=1;foreach($_productCollection as $_productData): ?>
      <?php $_product = Mage::getModel('catalog/product')->load($_productData['entity_id']); ?>
		<li>
			<a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
				<img class="hoverImg" src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(200); ?>" 
					alt="<?php echo $this->htmlEscape($_product['name']); ?>"  />
			</a>
			<div class="quickContent">
				<!-- Product Title -->
				<h2 class="product-name"> 
					<?php if($config['quick_new_name_character']!=''):?>
						<?php echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'),0, $config['quick_new_name_character'])?>
					<?php else:?>
						<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> 
					<?php endif;?> 
				</h2>
				<!-- End Product Title -->
				<!-- Rating -->
                        <?php echo $this->getReviewsSummaryHtml($_product, "short", true);?>
				<!-- End rating -->
				
				<!--Price-->  
					<?php echo $this->getPriceHtml($_product, true, '-right');?>
					<?php if($_product->getSpecialPrice()): ?>
						<?php echo Mage::helper("myfunction")->specialPriceDiscount($_product); ?>
					<?php endif; ?>
				<!--End price--> 
				
			</div>
		</li>
	<?php endforeach ?>	
	</ul>	
<?php endif; ?>
</div>
<?php endif; ?>
