<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<?php 
	$config = Mage::getStoreConfig('mdlpump/product-type-option'); 
	$config2 = Mage::getStoreConfig('mdlpump/upsellsetting');
?>
<?php if($config['product-view-option']==1): ?>
	<?php $classnNum ='col-md-9 areaBox'?>
<?php else:?>
	<?php $classnNum ='col-md-12 areaBox'?>
<?php endif; ?>


<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
  <div class="product-view <?php echo $classnNum; ?>">
    <div class="product-essential">
      <div class="row">
        <div class="product-img-box <?php if($config['product-view-option'] ==2):?> col-sm-6<?php else:?>col-sm-5<?php endif;?>"> <?php echo $this->getChildHtml('media') ?> </div>
        <div class="productDetailBox <?php if($config['product-view-option'] ==2):?> col-sm-6<?php else:?>col-sm-7<?php endif;?>">
          <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <div class="no-display">
              <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
              <input type="hidden" name="related_product" id="related-products-field_1" value="" />
            </div>
            <div class="product-shop">
              <div class="product_left f-fix">
                
				<?php $categoryId = Mage::registry('current_product')->getCategoryId();
				if($categoryId){
						$_prev = Mage::helper('mdl_prevnext')->getPreviousProduct();
						$_next = Mage::helper('mdl_prevnext')->getNextProduct();
				}else{
					$_prev = Mage::helper('mdl_prevnext')->getHomePreviousProduct();
					$_next = Mage::helper('mdl_prevnext')->getHomeNextProduct();
				} ?>
					<?php if($_prev || $_next): ?>
						<div class="productNav">
    
							<?php if($_prev): ?>
								<a rel="prev" class="prev_product" href="<?php echo $_prev->getProductUrl(); ?>">
									<span class="prev_pro_detail" style="display:none;">
										<?php echo substr($this->escapeHtml($_prev->getName()),0,10 ); ?>
										<img src="<?php echo $this->helper('catalog/image')->init($_prev, 'small_image')->resize(100, 100); ?>" alt="<?php echo $this->escapeHtml($_prev->getName()); ?>" />
									</span>
									<i class="fa fa-angle-left"></i>
								</a>
								<?php /* #inchoo_prevnext_prev */ ?>
							<?php endif; ?>

							<?php if($_next): ?>
								<a href="<?php echo $_next->getProductUrl(); ?>" rel="next" class="next_product">
									<span class="next_pro_detail" style="display:none;">
										<?php echo substr($this->escapeHtml($_next->getName()),0,10 ); ?>
										<img src="<?php echo $this->helper('catalog/image')->init($_next, 'small_image')->resize(100,100); ?>" alt="<?php echo $this->escapeHtml($_next->getName()); ?>" />				
									</span>
									<i class="fa fa-angle-right"></i>
								</a> 
								<?php /* #inchoo_prevnext_next */ ?>
							<?php endif; ?>
						</div>
					<?php endif; ?>
				
				
				
                <div class="product-name">
                  <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                </div>
				<?php if($config['product-view-option'] ==2): ?>
				<div class="widthBrand">
				<?php endif;?>
					<div class="extra-info"> <?php echo $this->getChildHtml('product_type_availability'); ?>
					  <div class="review"> <?php echo $this->getReviewsSummaryHtml($_product, false, true)?> </div>
					</div>
					<?php if ($_product->getShortDescription()):?>
					<div class="short-description">
					  <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
					</div>
					<?php endif;?>
					
					<div class="price_box"> 
						<?php echo $this->getPriceHtml($_product); ?> 
						<?php echo $this->getChildHtml('bundle_prices');?> 
						<?php echo $this->getTierPriceHtml();?> 
					</div>
					<?php if($_product->getSpecialPrice()): ?>
							<?php echo Mage::helper("myfunction")->specialPriceDiscount($_product); ?>
					<?php endif; ?>
					
					<?php if($config['product-view-option'] ==2): ?>
						<!--Brnad logo-->		
	
									<?php $isModuleEnable=false; $moduleName = 'Mdl_Brand'; ?>
										<?php if (Mage::helper('core')->isModuleEnabled($moduleName)) : ?>
											<?php $isModuleEnable=true; ?>
										<?php endif;?>
										<?php if($isModuleEnable): ?>
											<?php $typeId=$_product->getTypeId();?>
												<?php $brandOptionValue=$_product->getData('brand'); $brandHtml='';?>
												 
												<?php if($brandOptionValue) :?>
													<?php $brandHtml=Mage::helper('brand/data')->getBrandByOption($brandOptionValue);?>
												<?php else:?>
													<?php $brandHtml=Mage::helper('brand/data')->getBrandById($_product->getId());?>
												<?php endif ;?>
												
												<?php if($brandHtml!=''):?>
													<div class="brand"><?php echo $brandHtml;?></div>
												<?php endif;?>
												
										<?php endif ;?> 
						<!--End brnad logo-->	
					
				</div>
				<?php endif;?>	
				
				
				
				
				
                <?php $SizeChartUrl = Mage::getBaseUrl('media').'catalog/product/'.$_product->getMdlSizeChart();?>
                <?php if($_product->getMdlSizeChart()!='' && $_product->getMdlSizeChart()!='no_selection' ):?>
                <div class="sizeChartBox"> <a class="sizeChart" rel="example_group" href="<?php echo $SizeChartUrl;?>"><?php echo $this->__('Size Chart');?></a> </div>
                <?php endif;?>
                <div class="pro-left">
                  <div class="add_to_cart <?php if ($this->hasOptions()):?>optionB<?php endif;?>">
                    <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                      <?php if($_product->isSaleable()): ?>
                      <?php echo $this->getChildHtml('addtocart') ?>
                      <?php endif; ?>
                    </div>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('other');?>
                    <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true);?>
                    <?php endif;?>
                    <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true); ?>
                    <?php endif;?>
                    
					
                    <div class="clear"></div>
                  </div>
                  <div class="f-fix sbox"> <?php echo $this->getChildHtml('extrahint') ?>
                    <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                    <?php endif; ?>
					<?php echo $this->getChildHtml('addto');?>
                    <div class="mailRev">
                      <p><?php echo $this->__('Share with friends');?></p>
                      <!-- Go to www.addthis.com/dashboard to customize your tools -->
						<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55f129af836bfe51" async="async"></script>
						<!-- Go to www.addthis.com/dashboard to customize your tools -->
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mdl_addthis')->toHtml();?> 
					  </div>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="product-collateral" id="tabs"> <?php echo $this->getChildHtml('info_tabs') ?> </div>
    </div>
  </div>
 
 
 
  <?php if($config['product-view-option'] !=2): ?>
  <div class="product_right col-md-3 sidebar">
	
	<!--Brnad logo-->		
	
		        <?php $isModuleEnable=false; $moduleName = 'Mdl_Brand'; ?>
					<?php if (Mage::helper('core')->isModuleEnabled($moduleName)) : ?>
						<?php $isModuleEnable=true; ?>
					<?php endif;?>
					<?php if($isModuleEnable): ?>
						<?php $typeId=$_product->getTypeId();?>
							<?php $brandOptionValue=$_product->getData('brand'); $brandHtml='';?>
							 
							<?php if($brandOptionValue) :?>
								<?php $brandHtml=Mage::helper('brand/data')->getBrandByOption($brandOptionValue);?>
							<?php else:?>
								<?php $brandHtml=Mage::helper('brand/data')->getBrandById($_product->getId());?>
							<?php endif ;?>
							
							<?php if($brandHtml!=''):?>
								<div class="brand areaBox"><?php echo $brandHtml;?></div>
							<?php endif;?>
							
					<?php endif ;?> 
	<!--End brnad logo-->
  
    
    	<?php if($config2['upsellblocks']==1):?>
    		<?php echo $this->getChildHtml('upsell_products'); ?>
    	<?php elseif($config2['upsellblocks']==2):?>
    		<?php if($_product->getUpsellProducts()): ?>
    			<?php echo $this->getChildHtml('upsell_products'); ?>
    		<?php else: ?>
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('product_custom_block')->toHtml();?> 
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('product-static-box')->toHtml();?>
		    <?php endif;?>
    	<?php elseif($config2['upsellblocks']==3):?>
    		<?php echo $this->getChildHtml('upsell_products'); ?> 
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('product_custom_block')->toHtml();?> 
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('product-static-box')->toHtml();?> 
    	<?php endif;?>
  </div>
  <?php endif; ?>
 
<?php if($config['product-view-option'] ==2):?>
<?php echo $this->getChildHtml('upsell_products'); ?>
<?php endif; ?>
<?php //echo $this->getChildHtml('upsell_products'); ?>
<?php //echo $this->getChildHtml('related'); ?>
<script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script> 
<script type="text/javascript">
    	jQuery(document).ready(function(){
			jQuery("a[rel=example_group]").fancybox({
				hideOnContentClick  : true,
				showNavArrows       : false,
			    arrows              : false,
			    showTitle           : false,
			    scrolling           : 'no', 
				'transitionIn'		: 'none',
				'transitionOut'		: 'none',
				'titlePosition' 	: 'over',
				'titleFormat'		: function(title, currentArray, currentIndex, currentOpts) {
					return '<span id="fancybox-title-over">Image ' + (currentIndex + 1) + ' / ' + currentArray.length + (title.length ? ' &nbsp; ' + title : '') + '</span>';
				}
			});
		



});
    </script> 