<?php if (Mage::getStoreConfigFlag('mdlpump/item_view/ajaxdownslide')): ?>
<?php 
$productListMode = Mage::getStoreConfig('catalog/frontend/list_mode');
if ($productListMode == 'grid-list')
	$productListMode = 'grid';
elseif ($productListMode == 'list-grid')
	$productListMode = 'list';

if ($this->getRequest()->getParam('mode')) {
	if($this->getRequest()->getParam('mode') == 'grid')
		$productListMode = 'grid';
	else
		$productListMode = 'list';
}
?>
<script type="text/javascript">
var vMode = ('<?php echo  $productListMode;?>' == 'grid' ? '.products-grid' : '.products-list');
</script>
<?php endif; ?>

