<?php
    $class = 'ajax_'.md5(json_encode($block->getData()));
?>
<div class="<?php echo $class ?>">
	<!--
    <div class="icon-loading"><span>Loading...<span></div>
	-->
    <div data-role="loader" class="loading-mask loading-dark">
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...') ?>">
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
	".<?php echo $class ?>":{
		"Codazon_ProductFilter/js/firstload":{
			"ajaxUrl": "<?php echo $this->getUrl('productfilter/index/firstLoad') ?>",
			"currentUrl": "<?php echo $this->getUrl() ?>",
			"jsonData": <?php echo $block->getJsonData() ?>
		}
	}
}
</script>
