<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php //if($block->customerLoggedIn()): ?>          
        <?php //if($block->getChildHtml()):?>        
            <?php //echo $block->getChildHtml();?>        
        <?php //endif; ?>    
<?php //endif; ?>



<?php 
	//loads customer name faster than data-bind
    $om = \Magento\Framework\App\ObjectManager::getInstance();
    //$customerSession = $om->get('Magento\Customer\Model\Session'); NOT SHOWING USERNAME ON CMS PAGES
    $customerSession = $om->create('Magento\Customer\Model\Session');
?>
<?php if($block->customerLoggedIn()): ?>
    <?php 
    /*    */
        $firstname = $customerSession->getCustomer()->getFirstname(); 
        $returnHtml =  '<div class="avatar"><span>'. $firstname[0] .'</span></div>';
        $returnHtml .= '<div class="welcome-name"><span>'. $firstname.'licious</span></div>';
        //echo $returnHtml;
    ?>

    <li class="customer-welcome">
        <span class="customer-name"
              role="link"
              tabindex="0"
              data-mage-init='{"dropdown":{}}'
              data-toggle="dropdown"
              data-trigger-keypress-button="true"
              data-bind="scope: 'customer'">
            <?php echo $returnHtml; ?>
            <!--
            <div class="avatar"><span data-bind="text: new String(customer().firstname[0])"></span></div>
            <div class="welcome-name"><span data-bind="text: new String(customer().firstname +'licious')"></span></div>
            -->
            <button type="button"
                    class="action switch"
                    tabindex="-1"
                    data-action="customer-menu-toggle">
                <span><?php /* @escapeNotVerified */ echo __('Change')?></span>
            </button>
        </span>
        <?php if($block->getChildHtml()):?>
        <div class="customer-menu" data-target="dropdown">
            <ul>
	            <?php echo $block->getChildHtml();?>
        	</ul>
        </div>
        <?php endif; ?>
    </li>
<?php endif; ?>
