<div id="back-ajax-add" class="back-ajax-add">
<a class="axcart" href="javascript:void(0);" title="<?php echo $this->__('Continue shopping');?>" onclick="hideMdlOverlay();"><?php echo $this->__('Continue shopping');?></a>
<a class="axcart right" href="<?php echo $this->getUrl('checkout/cart'); ?>" title="<?php echo $this->__('View cart');?>">
	<?php echo $this->__('View cart');?>
</a>


</div>

<div id="cart_content" class="cart_content"><?php
$count = Mage::helper('checkout/cart')->getSummaryCount();

if( $count == 1 ) {
    echo $this->__('My Cart (%s item)', $count);
} elseif( $count > 0 ) {
    echo $this->__('My Cart (%s items)', $count);
} else {
    echo $this->__('My Cart');
}
?></div>
<div class="cart_side_ajax">
    <?php echo $this->getChildHtml('cart_sidebar_ajax') ?>
</div>
<div class="mdl_ajax_message">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<div class="mdl_full_cart_content" id="mdl_full_cart_content">
    <?php echo $this->getChildHtml('cart_content_ajax');?>
</div>