<?php

	$config = Mage::getStoreConfig('mdloption/item_view');
	$config2 = Mage::getStoreConfig('mdloption/genral_theme_setting');
	$config3 = Mage::getStoreConfig('mdlmdlnavi/navsettings');
	
    $_productCollection=$this->getLoadedProductCollection();
    $columnCount = Mage::getStoreConfig('mdloption/item_view/column_count');//mdlList('column_count');
    $this->setColumnCount($columnCount);
    $_helper = $this->helper('catalog/output');
?>
<!--code start-->

<!--If products  are not available-->

<?php if(!$_productCollection->count()): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>

<?php else: ?>
<div class="category-products f-block">
  <?php if($config['flip_view']==1 && $config['list_flip_view_style']==2):?>
  <?php $flipviewStyleL='fadeView'; ?>
  <?php endif; ?>
  <!--Toolbar--> 
  <?php echo $this->getToolbarHtml() ?> 
  <!--end Toolbar--> 
  <!--List View-->
  
  <?php if($this->getMode()!='grid'): ?>
  <?php $_iterator = 0; ?>
  <?php $imgSize = 192; ?>
  <ol class="products-list" id="products-list">
   <?php foreach ($_productCollection as $_product): ?>
			<li class="item<?php if( ++$_iterator == sizeof($_productCollection) ):?> last<?php endif; ?> firstView">
				<div class="itemInner areaBox <?php echo $flipviewStyleL; ?>">
        	
                <!--Images and price container-->
                    
                   <?php if($config['flip_view']==1):?>
                       <div class="proImage <?php echo $flipviewStyleL; ?> flipView">
					<!--Badge view-->
						<div class="badge">
						  <?php if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
						  <?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
						</div>
					<!--end badge view-->
                            <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
                            <img class="spacer-img" src="<?php echo $this->getSkinUrl('images/spacer.png');?>" title="" alt="" />
                            <span class="face"><img id="product-collection-image-<?php echo $_product->getId(); ?>" class="front-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"  /></span>
                            <span class="back-img face back">
                                <img class="hoverImg" src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(300); ?>" 
                                alt="<?php echo $this->htmlEscape($_product['name']); ?>"  />
                            </span> 
                            </a>
					  <!--Quick view icon-->
						  <?php if($config['itemviewbox_quick_view']==1):?>
						  <a title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox qv-btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i> <?php echo $this->__('Quick View');?></a>
						  <?php endif; ?>
					  <!--End quick view icon-->
                            </div>
                        <?php else: ?>
                        	<div class="proImage">
                            <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
                            </a>
												  <!--Quick view icon-->
						  <?php if($config['itemviewbox_quick_view']==1):?>
						  <a title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox qv-btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i><?php echo $this->__('Quick View');?></a>
						  <?php endif; ?>
					  <!--End quick view icon-->
                            </div>
                    <?php endif; ?>
                    
				<!--End images and price container--> 
                
                
                <!--Product detail container-->              
                <div class="bottomProDetail">
                	
                    <h2 class="product-name"> 
                    	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"> 
							<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> 
                        </a> 
                    </h2>
					
					<!-- Color swatch -->
					<?php if($_product->getTypeId()=='configurable'): ?>
							 <?php $_nameAfterChild = $this->getLayout()->createBlock('core/template')->setTemplate('configurableswatches/catalog/product/list/swatches.phtml');?>
                            <?php $_nameAfterChild->setProduct($_product);?>
							<div class="listColorSwatch ajaxswatch">
                            <?php echo $_nameAfterChild->toHtml();?>
							</div>
					<div class="product-media-<?php echo $_product->getId(); ?>" style="display: none;">
						<?php $count=0; $_product->load('media_gallery'); foreach($_product->getMediaGalleryImages() as $pimg): ?>
							<?php if($pimg->getLabel()!=''): ?>
							<?php $exLabel = explode('-swatch',$pimg->getLabel()); ?>
							<?php if(count($exLabel)>1): ?>
							<?php $pids=Mage::getResourceSingleton('catalog/product_type_configurable')->getChildrenIds($_product->getId());
								  $_psubproducts = Mage::getModel('catalog/product')->getCollection()->addIdFilter ($pids)
									->addAttributeToSelect('color')->addAttributeToSelect('small_image')->groupByAttribute('color'); ?>
							<?php foreach($_psubproducts as $_sprod): ?>
								<span class="swatch-<?php echo str_replace(' ','',strtolower($_sprod->getAttributeText('color')));  ?>"><?php echo $this->helper('catalog/image')->init($_sprod, 'small_image')->resize(300); ?></span>
							<?php endforeach; ?>
								<?php else: ?>
								<span class="swatch-<?php echo strtolower($pimg->getLabel());  ?>"><?php echo $pimg->getUrl(); ?></span>
								<?php endif; ?>
								<?php $count++; endif; ?>
						<?php endforeach; ?>
						<?php if($count==0): ?>
							<?php 	$ids=Mage::getResourceSingleton('catalog/product_type_configurable')->getChildrenIds($_product->getId());
									$_subproducts = Mage::getModel('catalog/product')->getCollection()->addIdFilter ($ids)
									->addAttributeToSelect('color')->addAttributeToSelect('small_image')->groupByAttribute('color'); ?>
							<?php	foreach($_subproducts as $_prod): ?>
									<span class="swatch-<?php echo trim(strtolower($_prod->getAttributeText('color')));  ?>"><?php echo $this->helper('catalog/image')->init($_prod, 'small_image')->resize(300); ?></span>
							<?php endforeach; ?>
						<?php  endif; ?>
						<span class="swatch-default"><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?></span>
					</div>
				<?php endif; ?>
					 <!--End Color swatch -->
					
					
                    <?php if($_product->getRatingSummary()): ?>
                    <?php endif; ?>
                    <div class="desc std">
                        <p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="read-btn"><?php echo $this->__('Read More') ?></a>
                    </div>
					

                    <!--Price-->  
                        <?php echo $this->getPriceHtml($_product, true, '-right') ?>
						<?php if($_product->getSpecialPrice()): ?>
							<?php echo Mage::helper("myfunction")->specialPriceDiscount($_product); ?>
						<?php endif; ?>
                    <!--End price-->  
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <div class="proAction">
                    	<!--Quick view-->
							  <?php if($config['itemviewbox_quick_view']==1):?>
								  <?php if($_product->isSaleable()): ?>
									  <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
                                      <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('<i class="fa fa-shopping-cart"></i>  Add to cart') ?></span></span></button>
                                      <?php else: ?>
                                      <a title="<?php echo $this->__('Add to Cart') ?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox add-cart' id='fancybox<?php echo $_product->getId();?>'><span><span><?php echo $this->__('<i class="fa fa-shopping-cart"></i>  Add to cart') ?></span></span></a>
                                      <?php endif; ?>
                                  <?php else: ?>
                                  	   <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                  <?php endif; ?>
                              <?php else: ?>
								  <?php if($_product->isSaleable()): ?>
                                  <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-cart f-right" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                  <?php else: ?>
                                  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                  <?php endif; ?>
                              <?php endif; ?>
                         <!--end quick view-->
                         
                         <!--Comapare-->
						 <?php if ($config2['compare_box']) :?>
							 <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                             	  <a title="<?php echo $this->__('Add to Compare') ?>" href="#" onclick="setLocation('<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" class="w-btn"><?php echo $this->__('<i class="fa fa-exchange"></i>') ?></a>
                             <?php endif; ?>
						<?php endif; ?>	 
                         <!--End comapare-->
                          
                          <!--wishlist-->
							  <?php if ($this->helper('wishlist')->isAllow()) : ?>
                              <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="w-btn"><i class="fa fa-heart"></i></a>
                              <?php endif; ?>
                          <!--End wishlist-->
    
                    </div>
                <!--End product detail container-->     
        </div>
        </div> 
      </li>
       <?php endforeach; ?>
  </ol>
  <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
  <?php else: ?>
  
  <!--end List View-->
  
  <?php $_collectionSize = $_productCollection->count() ?>
  <?php 
        $_columnCount = $this->getColumnCount(); 
		if($_columnCount == 4){
		$listWidth = 'col-xs-6 col-lg-3';
        $imgSize = 155;
        }elseif($_columnCount == 3){
			$listWidth = 'col-xs-6 col-sm-4';
            $imgSize = 245;
      } 
    ?>
  
  <!--Grid view-->
  
  <?php $i=0; foreach ($_productCollection as $_product): ?>
  <?php if ($i++%$_columnCount==0): ?>
  <ul class="products-grid itemPro">
   <?php endif; ?>
  	 	<?php if($config['itemviewbox']==1){
       		$itmeView = 'firstView';
	  	 }elseif($config['itemviewbox']==2){
       		$itmeView = 'secView';
		 }else{
			 $itmeView = 'thirdView';
		 };?>
         
   
      	<li class="item <?php echo $itmeView;?> <?php if(($i-1)%$_columnCount==0): ?> first <?php elseif($i%$_columnCount==0): ?> last <?php endif; ?><?php echo $listWidth ?>">
        	<div class="itemInner areaBox">
					
                <!--Images and price container-->
                    <div class="proImage <?php echo $flipviewStyleL; ?> flipView">
						<!--Badge view-->
						<div class="badge">
						<?php if($_product->getAttributeText('mdl_new')=='Yes'){echo '<span class="new"><b>'. $_product->getAttributeText('mdl_new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
						<?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
						</div>
						<!--end badge view-->
                   		<?php if($config['flip_view']==1):?>
                        <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
                        <img class="spacer-img" src="<?php echo $this->getSkinUrl('images/spacer.png');?>" title="" alt="" />
                        <span class="face pimage-<?php echo $_product->getId() ?>">
						<img id="product-collection-image-<?php echo $_product->getId(); ?>" class="front-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"  />
						</span>
                        <span class="back-img back face">
                            <img class="hoverImg" src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(300); ?>" 
                            alt="<?php echo $this->htmlEscape($_product['name']); ?>"  />
                        </span> 
                        </a>
                        
                        <?php else: ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
                            </a>
                    <?php endif; ?>
					
                          <?php if($config['itemviewbox']==1):?>
                          <!--Quick view icon-->
							  <?php if($config['itemviewbox_quick_view']==1):?>
                              <a  title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox qv-btn' id='itemviewboxfancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i> <?php echo $this->__('Quick View');?></a>
                              <?php endif; ?>
                          <!--End quick view icon-->
                           <?php endif; ?>
                          
                          <!--Quick links-->
                          <?php if($config['itemviewbox']==3):?>
                           <div class="qlinks">
                             <!--Comapare-->
							 <?php if ($config2['compare_box']) :?>
                                 <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                      <a href="javascript:void(0);" class="w-btn" onclick="setLocation('<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" > 
                                            <i class="fa fa-exchange"></i> 
                                      </a>
                                 <?php endif; ?>
							<?php endif; ?>	 
                             <!--End comapare-->
                              
                             <!--wishlist-->
                                  <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                  <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>"  class="w-btn">
                                     <i class="fa fa-heart"></i>
                                  </a>
                                  <?php endif; ?>
                             <!--End wishlist-->
                             
                             <!--Quick view icon-->
                                  <?php if($config['itemviewbox_quick_view']==1):?>
                                  <a   title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox w-btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i></a>
                                  <?php endif; ?>
                             <!--End quick view icon-->
                            </div> 
                          <?php endif; ?> 
                          <!--End Quick links-->
						  
					
                    </div>
				<!--End images and price container--> 
                
				<!--Product detail container-->  
				
				
                <div class="bottomProDetail 1">
				
					<!-- Color swatch -->
					<?php if($_product->getTypeId()=='configurable'): ?>
							 <?php $_nameAfterChild = $this->getLayout()->createBlock('core/template')->setTemplate('configurableswatches/catalog/product/list/swatches.phtml');?>
                            <?php $_nameAfterChild->setProduct($_product);?>
							<div class="listColorSwatch ajaxswatch">
                            <?php echo $_nameAfterChild->toHtml();?>
							</div>
					<div class="product-media-<?php echo $_product->getId(); ?>" style="display: none;">
						<?php $count=0; $_product->load('media_gallery'); foreach($_product->getMediaGalleryImages() as $pimg): ?>
							<?php if($pimg->getLabel()!=''): ?>
							<?php $exLabel = explode('-swatch',$pimg->getLabel()); ?>
							<?php if(count($exLabel)>1): ?>
							<?php $pids=Mage::getResourceSingleton('catalog/product_type_configurable')->getChildrenIds($_product->getId());
								  $_psubproducts = Mage::getModel('catalog/product')->getCollection()->addIdFilter ($pids)
									->addAttributeToSelect('color')->addAttributeToSelect('small_image')->groupByAttribute('color'); ?>
							<?php foreach($_psubproducts as $_sprod): ?>
								<span class="swatch-<?php echo str_replace(' ','',strtolower($_sprod->getAttributeText('color')));  ?>"><?php echo $this->helper('catalog/image')->init($_sprod, 'small_image')->resize(300); ?></span>
							<?php endforeach; ?>
								<?php else: ?>
								<span class="swatch-<?php echo strtolower($pimg->getLabel());  ?>"><?php echo $pimg->getUrl(); ?></span>
								<?php endif; ?>
								<?php $count++; endif; ?>
						<?php endforeach; ?>
						<?php if($count==0): ?>
							<?php 	$ids=Mage::getResourceSingleton('catalog/product_type_configurable')->getChildrenIds($_product->getId());
									$_subproducts = Mage::getModel('catalog/product')->getCollection()->addIdFilter ($ids)
									->addAttributeToSelect('color')->addAttributeToSelect('small_image')->groupByAttribute('color'); ?>
							<?php	foreach($_subproducts as $_prod): ?>
									<span class="swatch-<?php echo trim(strtolower($_prod->getAttributeText('color')));  ?>"><?php echo $this->helper('catalog/image')->init($_prod, 'small_image')->resize(300); ?></span>
							<?php endforeach; ?>
						<?php  endif; ?>
						<span class="swatch-default"><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?></span>
					</div>
				<?php endif; ?>
					 <!--End Color swatch -->
				
				
                	<h2 class="product-name"> 
                    	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"> 
                        	<?php if($config['name_character']!=''):?>
                            	<?php echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'),0, $config['name_character'])?>
                            <?php else:?>
                            	<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> 
                            <?php endif;?>        
                        </a> 
                    </h2>
					
					
                    
					<!-- Rating -->
                        <?php echo $this->getReviewsSummaryHtml($_product, "short", true)?>
                    <!-- End rating -->
					
                    <!--Price-->  
                        <?php echo $this->getPriceHtml($_product, true, '-right') ?>
						<?php if($_product->getSpecialPrice()): ?>
							<?php echo Mage::helper("myfunction")->specialPriceDiscount($_product); ?>
						<?php endif; ?>
                    <!--End price--> 
					
                    <div class="proAction">
                    	<?php if(($config['itemviewbox']==1)||($config['itemviewbox']==3)):?>
                        
							  <?php if($config['itemviewbox_quick_view']==1):?>
								  <?php if($_product->isSaleable()): ?>
									  <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
                                      <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to cart') ?></span></span></button>
                                      <?php else: ?>
                                      <a title="<?php echo $this->__('Add to Cart') ?>"  href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox add-cart' id='fancybox<?php echo $_product->getId();?>'><span><span><?php echo $this->__('Add to cart') ?></span></span></a>
                                      <?php endif; ?>
                                  <?php else: ?>
                                  	   <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                  <?php endif; ?>
                              <?php else: ?>
								  <?php if($_product->isSaleable()): ?>
                                  <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                  <?php else: ?>
                                  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                  <?php endif; ?>
                              <?php endif; ?>
                         <!--end quick view-->
                         
                       <?php elseif($config['itemviewbox']==2):?>
                       			<?php if($config['fp_quick_view']==1):?>
                                      <?php if($_product->isSaleable()): ?>
                                          <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
                                          <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="w-btn" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i></span></span></button>
                                          <?php else: ?>
                                          <a title="<?php echo $this->__('Add to Cart') ?>"  href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox w-btn' id='fancybox<?php echo $_product->getId();?>'><span><span><i class="fa fa-shopping-cart"></i></span></span></a>
                                          <?php endif; ?>
                                      <?php else: ?>
                                           <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                      <?php endif; ?>
                                  <?php else: ?>
                                      <?php if($_product->isSaleable()): ?>
                                      <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="w-btn" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i></span></span></button>
                                      <?php else: ?>
                                      <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                      <?php endif; ?>
                                  <?php endif; ?>
                       
                       <?php endif;?>  
                         
                         
                         
                        <?php if(($config['itemviewbox']==1)||($config['itemviewbox']==2)):?> 
                             <!--Comapare-->
							<?php if ($config2['compare_box']) :?>
                                 <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                      <a href="javascript:void(0);" class="w-btn" onclick="setLocation('<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" > 
                                            <i class="fa fa-signal"></i> 
                                      </a>
                                 <?php endif; ?>
							<?php endif; ?>	 
                             <!--End comapare-->
                              
                              <!--wishlist-->
                                  <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                  <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>"  class="w-btn">
                                     <i class="fa fa-heart"></i>
                                  </a>
                                  <?php endif; ?>
                              <!--End wishlist-->
                              
                               <?php if($config['itemviewbox']==2):?>
                              <!--Quick view icon-->
                                      <?php if($config['itemviewbox_quick_view']==1):?>
                                      <a   title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox w-btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i></a>
                                      <?php endif; ?>
                              <!--End quick view icon-->
                              <?php endif;?>
                          <?php endif;?> 
                          

                    </div>
                    
                    
                    
                    
                    
                </div>
                <!--End product detail container-->     
        </div>
        </li>

    	
    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
	
	
	
  </ul>
  <?php endif ?>
  <?php endforeach ?>
  <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
  <?php endif; ?>
  <div class="toolbar-bottom"> <?php echo $this->getToolbarHtml() ?> </div>
  
  </div>
<?php endif; ?>

<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
<script type="text/javascript">
		
	jQuery(document).ready(function(){
		jQuery(".namePan").selectbox();
		jQuery(".showPan").selectbox();
		
		jQuery(".mdl_layered_attribute, .mdl_layered_clear").off('click').on("click", function(){
		<?php if ($config3['nav-fix']):?>
		  jQuery('html,body').animate({ scrollTop: jQuery('#mdl_layered_container').offset().top -50 }, 'slow');
		<?php else:?>
		  jQuery('html,body').animate({ scrollTop: jQuery('#mdl_layered_container').offset().top - 30 }, 'slow');	
		<?php endif;?>	
		});
		
		 jQuery("#slider").bind("valuesChanged", function(e, data){
			<?php if ($config3['nav-fix']):?>
			  jQuery('html,body').animate({ scrollTop: jQuery('#mdl_layered_container').offset().top - 50 }, 'slow');
			<?php else:?>
			  jQuery('html,body').animate({ scrollTop: jQuery('#mdl_layered_container').offset().top - 30 }, 'slow');	
			<?php endif;?>
		 });
		 
		jQuery('body').on('click','.ajaxswatch ul li a',function() {
			var myElement = jQuery(this);
			var Pid = myElement.parent().attr('data-product-id');
			var thisCol = myElement.find('img').prop('alt');
			var reqImag = jQuery('.product-media-'+Pid).find('.swatch-'+thisCol).html();
			var defImg =  jQuery('.product-media-'+Pid).find('.swatch-default').html();
			if (reqImag) {
               jQuery('.pimage-'+Pid).find('img').attr('src',reqImag);
            }
			else
			{
				jQuery('.pimage-'+Pid).find('img').attr('src',defImg);
			}
			});
		
	});
	
	
</script>
 
	