<?php

	$config = Mage::getStoreConfig('mdlpump/item_view');
	$config2 = Mage::getStoreConfig('mdloption/genral_theme_setting');
	$config3 = Mage::getStoreConfig('mdlmdlnavi/navsettings');
	
    $_productCollection=$this->getLoadedProductCollection();
    $columnCount = Mage::getStoreConfig('mdloption/item_view/column_count');//mdlList('column_count');
    $this->setColumnCount($columnCount);
    $_helper = $this->helper('catalog/output');
	
?>
<!--code start-->

<!--If products  are not available-->

<?php if(!$_productCollection->count()): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.');?></p>

<?php else: ?>
<div class="category-products f-block">

  <?php if($config['flip_view']==1 && $config['flip_view_style']==2):?>
	<?php $flipviewStyleL='fadeView'; ?>
  <?php endif; ?>
  <!--Toolbar--> 
  <?php echo $this->getToolbarHtml() ?> 
  <!--end Toolbar--> 
  
  
  
  <!--List View-->
  
  <?php if($this->getMode()!='grid'): ?>
  <?php $_iterator = 0; ?>
  <?php $imgSize = 192; ?>
  <ol class="products-list" id="products-list">
   <?php foreach ($_productCollection as $_product): ?>
			<li class="item<?php if( ++$_iterator == sizeof($_productCollection) ):?> last<?php endif; ?> firstView">
				<div class="itemInner areaBox <?php echo $flipviewStyleL; ?>">
        	
                <!--Images and price container-->
				
					<!--Badge view-->
						<div class="badgeBox">
						<!--New badge-->
							<?php if($_product->getData('mdl_new')):?>
								<span class="new">
									<strong><?php echo $this->__('new')?></strong>
								</span>
							<?php endif;?>
						<!--End new badge-->
						</div>
					<!--end badge view-->
					
                    
                   <?php if($config['flip_view']==1):?>
                       <div class="proImage <?php echo $flipviewStyleL; ?> flipView">
					        <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
                            <img class="spacer-img" src="<?php echo $this->getSkinUrl('images/spacer.png');?>" title="" alt="" />
                            <span class="face"><img id="product-collection-image-<?php echo $_product->getId(); ?>" class="front-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"  /></span>
                            <span class="back-img face back">
                                <img class="hoverImg" src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(300); ?>" 
                                alt="<?php echo $this->htmlEscape($_product['name']); ?>"  />
                            </span> 
                            </a>
					  <!--Quick view icon-->
						  <?php if($config['itemviewbox_quick_view']==1):?>
						  <a title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox qv-btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i> </a>
						  <?php endif; ?>
					  <!--End quick view icon-->
                            </div>
                        <?php else: ?>
                        	<div class="proImage">
                            <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
                            </a>
						
						<!--Quick view icon-->
						  <?php if($config['itemviewbox_quick_view']==1):?>
						  <a title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox qv-btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i></a>
						  <?php endif; ?>
					  <!--End quick view icon-->
                            </div>
                    <?php endif; ?>
                    
				<!--End images and price container--> 
                
                
                <!--Product detail container-->              
                <div class="bottomProDetail">
                	
                    <h2 class="product-name"> 
                    	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"> 
							<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> 
                        </a> 
                    </h2>
					
					<!-- Color swatch -->
					<?php if ($this->getChild('name.after')):?>
                        <?php $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();?>
                        <?php foreach ($_nameAfterChildren as $_nameAfterChildName):?>
                            <?php $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);?>
                            <?php $_nameAfterChild->setProduct($_product);?>
							<div class="listColorSwatch">
                            <?php echo $_nameAfterChild->toHtml();?>
							</div>
                        <?php endforeach ?>
                    <?php endif;?>
					 <!--End Color swatch -->
					
					
                    <?php if($_product->getRatingSummary()): ?>
                    <?php endif; ?>
                    <div class="desc std">
                        <p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="read-btn"><?php echo $this->__('Read More') ?></a>
                    </div>
					

                    <!--Price-->  
                        <?php echo $this->getPriceHtml($_product, true, '-right') ?>
						<?php if($_product->getSpecialPrice()): ?>
							<?php echo Mage::helper("myfunction")->specialPriceDiscount($_product); ?>
						<?php endif; ?>
                    <!--End price-->  
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <div class="proAction">
                    	<!--Quick view-->
							  <?php if($config['itemviewbox_quick_view']==1):?>
								  <?php if($_product->isSaleable()): ?>
									  <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
                                      <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('<i class="fa fa-shopping-cart"></i>  Add to cart') ?></span></span></button>
                                      <?php else: ?>
                                      <a title="<?php echo $this->__('Add to Cart') ?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox add-cart' id='fancybox<?php echo $_product->getId();?>'><span><span><?php echo $this->__('<i class="fa fa-shopping-cart"></i>  Add to cart') ?></span></span></a>
                                      <?php endif; ?>
                                  <?php else: ?>
                                  	   <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                  <?php endif; ?>
                              <?php else: ?>
								  <?php if($_product->isSaleable()): ?>
                                  <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-cart f-right" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                  <?php else: ?>
                                  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                  <?php endif; ?>
                              <?php endif; ?>
                         <!--end quick view-->
                         
                         <!--Comapare-->
						 <?php if ($config2['compare_box']) :?>
							 <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                             	  <a title="<?php echo $this->__('Add to Compare') ?>" href="#" onclick="setLocation('<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" class="w-btn"><?php echo $this->__('<i class="fa fa-clone"></i>') ?></a>
                             <?php endif; ?>
						<?php endif; ?>	 
                         <!--End comapare-->
                          
                          <!--wishlist-->
							  <?php if ($this->helper('wishlist')->isAllow()) : ?>
                              <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="w-btn"><i class="fa fa-heart"></i></a>
                              <?php endif; ?>
                          <!--End wishlist-->
    
                    </div>
                <!--End product detail container-->     
        </div>
        </div> 
      </li>
       <?php endforeach; ?>
  </ol>
  <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
  <?php else: ?>
  
  <!--end List View-->
  
  <?php $_collectionSize = $_productCollection->count() ?>
  <?php 
        $_columnCount = $this->getColumnCount(); 
		if($_columnCount == 4){
		$listWidth = 'col-xs-6 col-lg-3';
        $imgSize = 155;
        }elseif($_columnCount == 3){
			$listWidth = 'col-xs-6 col-sm-4';
            $imgSize = 245;
      } 
    ?>
  
  <!--Grid view-->
   <?php $i=0; foreach ($_productCollection as $_product): ?>
  <?php if ($i++%$_columnCount==0): ?>
  <ul class="products-grid itemPro">
   <?php endif; ?>
  	 	
       <!--Type 03-->
  
  <li class="item thirdView <?php if(($i-1)%$_columnCount==0): ?> first <?php elseif($i%$_columnCount==0): ?> last <?php endif; ?><?php echo $listWidth ?>">
        	<div class="itemInner areaBox">
					
                <!--Images and price container-->
                    <div class="proImage <?php echo $flipviewStyleL; ?> flipView">
						<!--Badge view-->
							<div class="badgeBox">
									<!--New badge-->
									<?php if($_product->getData('mdl_new')):?>
										<span class="new">
											<strong><?php echo $this->__('new')?></strong>
										</span>
									<?php endif;?>
									<!--End new badge-->
							</div>	
						<!--end badge view-->
						
						
						<!--Sale badge view-->
							<?php if($_product->getSpecialPrice()): ?>
                                <?php echo Mage::helper("myfunction")->specialPriceDiscount($_product); ?>
                            <?php endif; ?>
                        <!--End sale badge view-->
						
						
                   		<?php if($config['flip_view']==1):?>
							<a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
							<img class="spacer-img" src="<?php echo $this->getSkinUrl('images/spacer.png');?>" title="" alt="" />
							<span class="face pimage-<?php echo $_product->getId();  ?>">
							<img id="product-collection-image-<?php echo $_product->getId(); ?>" class="front-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"  />
							</span>
							<span class="back-img back face">
								<img class="hoverImg" src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(300); ?>" 
								alt="<?php echo $this->htmlEscape($_product['name']); ?>"  />
							</span> 
							</a>
                        <?php else: ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
                            </a>
						<?php endif; ?>
						
						
					
                          <!--Quick links-->
                           <div class="qlinks">
								 <!--Comapare-->
								<?php if ($config2['compare_box']) :?>
									 <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
										  <a href="javascript:void(0);" class="w-btn" onclick="setLocation('<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" > 
												<i class="fa fa-clone"></i> 
										  </a>
									 <?php endif; ?>
								<?php endif; ?>	 
								<!--End comapare-->
								  
								<!--wishlist-->
									  <?php if ($this->helper('wishlist')->isAllow()) : ?>
									  <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>"  class="w-btn">
										 <i class="fa fa-heart"></i>
									  </a>
									  <?php endif; ?>
								 <!--End wishlist-->
								 
								<!--Quick view icon-->
									  <?php if($config['itemviewbox_quick_view']==1):?>
									  <a   title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox w-btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i></a>
									  <?php endif; ?>
								<!--End quick view icon-->
								</div> 
                          <!--End Quick links-->
						  
					
                    </div>
				<!--End images and price container--> 
                
				<!--Product detail container-->  
				
				
                <div class="bottomProDetail">
					<div class="listColorSwatch">
					<!-- Color swatch -->
					<?php if ($this->getChild('name.after')):?>
                        <?php $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();?>
                        <?php foreach ($_nameAfterChildren as $_nameAfterChildName):?>
                            <?php $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);?>
                            <?php $_nameAfterChild->setProduct($_product);?>
							<div class="listColorSwatch">
                            <?php echo $_nameAfterChild->toHtml();?>
							</div>
                        <?php endforeach ?>
                    <?php endif;?>
					 <!--End Color swatch -->
					</div>
					
					<h2 class="product-name"> 
                    	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"> 
                        	<?php if($config['name_character']!=''):?>
                            	<?php echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'),0, $config['name_character'])?>
                            <?php else:?>
                            	<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> 
                            <?php endif;?>        
                        </a> 
                    </h2>
					
					<!-- Rating -->
                        <?php echo $this->getReviewsSummaryHtml($_product, "short", true)?>
                    <!-- End rating -->
					
                    <!--Price-->  
                        <?php echo $this->getPriceHtml($_product, true, '-right') ?>
					<!--End price--> 
					
					
					<div class="proAction">
								<?php if($config['itemviewbox_quick_view']==1):?>
									  <?php if($_product->isSaleable()): ?>
										  <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
										  <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to cart') ?></span></span></button>
										  <?php else: ?>
										  <a title="<?php echo $this->__('Add to Cart') ?>"  href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox add-cart' id='fancybox<?php echo $_product->getId();?>'><span><span><?php echo $this->__('Add to cart') ?></span></span></a>
										  <?php endif; ?>
									  <?php else: ?>
										   <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									  <?php endif;?>
								<?php else: ?>
									  <?php if($_product->isSaleable()): ?>
									  <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
									  <?php else: ?>
									  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									  <?php endif; ?>
								<?php endif; ?>
									
						</div>
					
                    
                    
                    
                    
                </div>
                <!--End product detail container-->     
        </div>
        </li>
  
  
  <!--End Type 03-->

    	
    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
	
	
	
  </ul>
  <?php endif ?>
  <?php endforeach ?>	
  
  
   <script type="text/javascript">
		(function($){
			$(function(){
					$('.listGallery').owlCarousel({
					loop:false,
					smartSpeed: 500,
					margin:10,
					dots: false,
					nav: true,
					navText: ["<i class='fa fa-angle-left'></i>", "<i class='fa fa-angle-right'></i>" ],
					responsiveClass:true,
					items:1
				})
					
			});
			
			$('li.item').each(function(index,v){
				var i = $(v).data('galcounter');
				$(document).on('click','li.galbox'+i+' a.galleryBtn',function(){
					$('li.item').addClass('galView');
					$('li.galbox'+i).removeClass('galView');
					return false;
				});
				$(document).on('click','li.galbox'+i+' a.closeGallery',function(){
					$('li.galbox'+i).addClass('galView');
					return false;
				});
			});
		})(jQuery);			
		</script>
  
  
  	
  
  <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
  <?php endif; ?>
  <div class="toolbar-bottom"> <?php echo $this->getToolbarHtml() ?> </div>
  
  </div>
<?php endif; ?>

<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>

<script type="text/javascript">
		
	jQuery(document).ready(function(){
		jQuery(".namePan").selectbox();
		jQuery(".showPan").selectbox();
		
		jQuery(".mdl_layered_attribute, .mdl_layered_clear").off('click').on("click", function(){
		<?php if ($config3['nav-fix']):?>
		  jQuery('html,body').animate({ scrollTop: jQuery('#mdl_layered_container').offset().top -50 }, 'slow');
		<?php else:?>
		  jQuery('html,body').animate({ scrollTop: jQuery('#mdl_layered_container').offset().top - 30 }, 'slow');	
		<?php endif;?>	
		});
		
		 jQuery("#slider").bind("valuesChanged", function(e, data){
			<?php if ($config3['nav-fix']):?>
			  jQuery('html,body').animate({ scrollTop: jQuery('#mdl_layered_container').offset().top - 50 }, 'slow');
			<?php else:?>
			  jQuery('html,body').animate({ scrollTop: jQuery('#mdl_layered_container').offset().top - 30 }, 'slow');	
			<?php endif;?>
		 });
		  
		
	});
	catalog_toolbar_init();
</script>	
	